### ISSUE TITLE
Browser support documentation needs more specificity

### ISSUE THREAD

**Issue by thiscompsciguy** [preactjs/preact-www#1048]
As a developer, I need to know the specific minimum version supported by preact so that I can determine my user base meets the minimum requirements.

The [current documentation](https://preactjs.com/about/browser-support/) only mentions "modern browsers" which isn't specific enough. 

For posterity the current documentation as of Jan 5 2024 is simply:

> Browser Support
> Preact supports modern browsers (Chrome, Firefox, Safari, Edge) and IE11. It works out of the box with these browsers and no additional polyfills are needed.

**Comment by rschristian** [comment]
> I need to know the specific minimum version supported by preact

IE11 is a pretty specific minimum, no?

**Comment by thiscompsciguy** [comment]
no as I need to support all major browsers. Android and iOS minimum
versions would be very helpful as my primary use cases are mobile. A break
down closer to https://caniuse.com/ would be extremely helpful.

**Comment by rschristian** [comment]
IE11 is supported and is more than a decade old, is my point. That's the lower bounds for support.

You're really not going to run into trouble on any sort of modern browser.

**Comment by thiscompsciguy** [comment]
I wont bet my business on what IE supported 10 years ago, especially given it is a deprecated technology. An update to the documentation that is explicit to Chromium and WebKit (Safari) is necessary. There are also differences in functionality between Sarafi/Chrome and Android WebView and especially with Safari and WkWebView. 

If it is as clear as you make out, please make the documentation clear.

**Comment by rschristian** [comment]
Does any other UI library offer that sort of breakdown? I haven't been able to find one, especially anything regarding webviews.

We list the minimums and unless someone in the community (you, perhaps?) wants to contribute more comprehensive docs I don't think we'll expand upon this.

And I don't mean to sound rude, but if you truly feel that this is a situation in which you're betting your business upon library choice, you probably shouldn't put all that faith into OSS (read: absolutely free, contributed by volunteers) docs. We're volunteers who contribute time when we can, no one is paid (well, beyond tangentially) to work on these docs. This is a pretty big demand given the number of environments and time range you want documented.

I'm sure we'd be happy to display your findings if you wanted to investigate this yourself though.

**Comment by thiscompsciguy** [comment]
Yes. As an example, something like this is exactly what would I expect -
https://create-react-app.dev/docs/supported-browsers-features/

**Comment by rschristian** [comment]
> Supported Browsers
>
> By default, the generated project supports all modern browsers. Support for Internet Explorer 9, 10, and 11 requires polyfills. For a set of polyfills to support older browsers, use [react-app-polyfill](https://github.com/facebook/create-react-app/blob/main/packages/react-app-polyfill/README.md).

Er, that's pretty close to what we list.

**Comment by rschristian** [comment]
I'm going to close this out as I don't think we can feasibly support what you're after.

Breaking down multiple browsers and webviews by version over the past decade+ is simply beyond our resources and not something **any** equivalent tooling offers. CanIUse and MDN browser compat data have hundreds of contributors and even then their data is can be iffy.

This is a huge ask. We'd be happy to display the data if you could provide it, but I think that's the extent of it.

**Comment by thiscompsciguy** [comment]
Sorry for any confusion. The ask wasn't for a break down by all browsers, but rather the set of internal browser APIs used. Something akin to this from the provided link:

> These modules ensure the following language features are present:
> 
> Promise (for async / await support)
> window.fetch (a Promise-based way to make web requests in the browser)
> Object.assign (a helper required for Object Spread, i.e. { ...a, ...b })
> Symbol (a built-in object used by for...of syntax and friends)
> Array.from (a built-in static method used by array spread, i.e. [...arr])

At any rate, I got the answers that I needed. Thank you.
