### ISSUE TITLE
Docs/Tutorial - explain when state is shared vs. unique to component instances

### ISSUE THREAD

**Issue by morandd** [preactjs/preact-www#1060]
Almost all the examples in the docs and tutorials show components with a single instance. For new users like myself it is very unclear when state is unique to each instance vs. shared across all component instances. 

For class components that descent from Component, it seems that this.state and this.setState is shared across all instances of that component. I had assumed that state was private to each Component instance. But it seems that the constructor is called once when the component is first used, then the render(props,state) method is called to create and refresh all instances. And when should we use this.state vs. using 'state' as passed in from render()?

This is fairly crucial to building larger projects in preact and I think may users would really appreciate an additional page in the tutorial about this.

**Comment by rschristian** [comment]
> For class components that descent from Component, it seems that this.state and this.setState is shared across all instances of that component.

This is not the case, no. and would generally make component useless (not to mention is entirely against the base ideas of OOP, but I digress).

Can you show an example of what you're referring to? [Here's component state being isolated by instance](https://preactjs.com/repl?code=aW1wb3J0IHugcmVuZGVyLCBDb21wb25lbnQgfSBmcm9tICdwcmVhY3QnOwppbXBvcnQgeyB1c2VTdGF0ZSB9IGZyb20gJ3ByZWFjdC9ob29rcyc7CgoKY2xhc3MgQ291bnRlciBleHRlbmRzIENvbXBvbmVudCB7CiAgICBzdGF0ZSA9IHsgY291bnQ6IDAgfQoKICAgIHJlbmRlcih7IG5hbWUgfSwgeyBjb3VudCB9KSB7CgkJCXJldHVybiAoCgkJCQk8PgoJCQkJCTxwPkNvdW50ZXIge25hbWV9PC9wPgoJCQkJCTxkaXYgc3R5bGU9e3sgbWFyZ2luTGVmdDogJzFyZW0nIH19PgoJCQkJCQk8cD5Db3VudDoge2NvdW50fTwvcD4KCQkJCQkJPGJ1dHRvbiBvbkNsaWNrPXsoKSA9PiB0aGlzLnNldFN0YXRlKHsgY291bnQ6IGNvdW50ICsgMSB9KX0%2BSW5jcmVtZW50PC9idXR0b24%2BCgkJCQkJPC9kaXY%2BCgkJCQk8Lz4KCQkJKTsKCQl9Cn0KCgpmdW5jdGlvbiBXcmFwcGVyKCkgewoJcmV0dXJuICgKCQk8PgoJCQk8Q291bnRlciBuYW1lPSIxIiAvPgoJCQk8Q291bnRlciBuYW1lPSIyIiAvPgoJCTwvPgoJKTsKfQoKcmVuZGVyKDxXcmFwcGVyIC8%2BLCBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYXBwJykpOwo%3D).

**Comment by morandd** [comment]
well, after 12 hours I discovered that newly created components need to have a unique "key" property otherwise Preact is likely to recycle a pre-existing instance and update it with the new props (that is, keeping the old state and not calling the constructor again).
