### ISSUE TITLE
Sketchy sponsor

### ISSUE THREAD

**Issue by parsec501** [preactjs/preact-www#1087]
Why is there an online casino "review" site with the domain name scams.info on your sponsor list prominently on the landing page?

The best part is that the "lead author" and "verified expert" has an AI-generated profile picture. You can tell by the left glass, it's a typical StyleGAN artefact and an issue with other architectures too.

Almost seems like the site has been hacked based on the domain name. They've even manually excluded it from the Internet Archive Wayback machine

**Comment by rschristian** [comment]
The sponsors on the home page are "Gold Sponsors" and higher, from the [Open Collective](https://opencollective.com/preact). This company is one of them.

I don't think it's worth getting into the philosophy of open source projects accepting donations from where they can get them, but do you have any particular issue with our implementation?
