### ISSUE TITLE
Broken link: component lifecycle diagram

### ISSUE THREAD

**Issue by tinymachine** [preactjs/preact-www#1094]
This link in `components.md` to the lifecycle diagram that Dan Abramov apparently tweeted is broken:

https://github.com/preactjs/preact-www/blob/e06b7f9eb9e0958f9b17c4a7efd8dbe14c72c32e/content/en/guide/v10/components.md?plain=1#L97

**Comment by rschristian** [comment]
Looks like you can grab it from the [internet archive](https://web.archive.org/web/20191118010106/https://twitter.com/dan_abramov/status/981712092611989509), if you (or anyone else) wanted to contribute a PR fixing this.

**Comment by rschristian** [comment]
Fixed in #1095
