### ISSUE TITLE
Can't run site in development mode

### ISSUE THREAD

**Issue by KiritaniAyaka** [preactjs/preact-www#1128]
The site can't run on my local machine. All things I do:

1. Clone this repo
2. Run `npm i` and `npm run dev`
3. Open localhost:8080

Then I got an error in the console as follows image and no contents rendered:

![image](https://github.com/preactjs/preact-www/assets/26200808/ea4f1e37-c27c-456f-b807-d569ca9cf647)

But it looks like the build output works fine, there are no error throws during building at least.

My Node.js version is 18.19.1

**Comment by rschristian** [comment]
Strange, what browser are you using?

I'm aware of an issue with our [logo component](https://github.com/preactjs/preact-www/blob/45c6e34a463143dec2d336f5956a3ddd7fec1c97/src/components/logo.jsx#L92-L93), but I haven't had any issue w/ running the site at all.

**Comment by KiritaniAyaka** [comment]
I'm using Chrome 124.0.6367.119 on Windows 11

---

I tried to fix this locally by changing two lines that have type issues to:

```typescript
onMouseOver={!touch ? this.hover : undefined}
onMouseOut={!touch ? this.hoverOut : undefined}
```

Now the index page can be rendered but there are some other errors.

![image](https://github.com/preactjs/preact-www/assets/26200808/5bcdf355-63c8-44cc-beb9-2fbc004abbaf)

When the browser requests `http://localhost:8080/.netlify/functions/release?repo=preact`, Vite crashes:

```
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:405:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:149:11)
    at defaultLoad (node:internal/modules/esm/load:99:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:416:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:287:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at #createModuleJob (node:internal/modules/esm/loader:311:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:264:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:250:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:335:23) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}

Node.js v18.19.1
```

I'm aware that 'c:' is the drive letter of Windows. So I tried running the site on my Fedora virtual machine and visited it on Windows, and everything worked fine.

So there is a compatibility issue for Windows except the type issue mentioned above. But I have no clue how to fix the compatibility issue.

**Comment by rschristian** [comment]
> When the browser requests http://localhost:8080/.netlify/functions/release?repo=preact, Vite crashes:

Crap, that'd be the [Netlify middleware](https://github.com/preactjs/preact-www/blob/master/plugins/netlify.js). Not quite sure what the pattern is on Windows, but those `path.join()` calls are probably the issue.

Thanks for looking into this, I really appreciate it.

> So I tried running the site on my Fedora virtual machine and visited it on Windows, and everything worked fine.

Just out of curiosity, did everything work fine with the patch to `onMouseover` etc.? As far as I can tell, that should be a valid error you're seeing so I'm a bit confused why that doesn't seem to happen on Linux, but I haven't been able to look into it yet.

**Comment by rschristian** [comment]
> I'm using Chrome 124.0.6367.119 on Windows 11

Oh, we check touchpoints for the logo to detect mobile. That makes sense why I didn't see anything (typical desktop for me).

We should be able to get rid of [`touch`](https://github.com/preactjs/preact-www/blob/45c6e34a463143dec2d336f5956a3ddd7fec1c97/src/components/logo.jsx#L80-L81) altogether and just do this:

```js
onMouseOver={this.hover}
onMouseOut={this.hoverOut}
```

Not quite sure why this was done to begin with.

**Comment by KiritaniAyaka** [comment]
> Just out of curiosity, did everything work fine without the patch to `onMouseover` etc.?

Without any patch, the type error is still thrown. Even though it runs on Linux.

**Comment by KiritaniAyaka** [comment]
> Crap, that'd be the [Netlify middleware](https://github.com/preactjs/preact-www/blob/master/plugins/netlify.js). Not quite sure what the pattern is on Windows, but those `path.join()` calls are probably the issue.

Thanks for this information I solved it quickly. Just add a `file://` before the file path works fine on Windows and Linux.

**Comment by rschristian** [comment]
Looks like we'll want [`url.pathToFileURL`](https://nodejs.org/api/url.html#urlpathtofileurlpath-options).

If you're willing to submit a PR I'll get that right in, else, I should be able to land this in the next day or so when I have a free moment.
