### ISSUE TITLE
TypeScript: Add docs on extending `IntrinsicElements` & `HTMLAttributes`

### ISSUE THREAD

**Issue by rschristian** [preactjs/preact-www#1145]
People often need to create global attrs or types for custom elements and, at the moment, that usually means slogging through issues to find the right config. We should document this better.

**Comment by ngdangtu-vn** [comment]
One case is Lume and its `inline` plugin:

- https://lume.land/plugins/inline/
- https://lume.land/plugins/jsx_preact/

![image](https://github.com/preactjs/preact-www/assets/68631458/afd8107a-cd9e-4934-8067-141fd81483de)

**Comment by rschristian** [comment]
@ngdangtu-vn If you have a couple minutes, I'd love to know your thoughts on https://deploy-preview-1151--preactjs.netlify.app/guide/v10/typescript#extending-built-in-jsx-types

Is there anything missing that you'd like to see? Would this have been useful to you?

**Comment by rschristian** [comment]
I don't think that's something Preact's types support at the moment -- we don't differentiate attributes by element type, there's `HTMLAttributes` (which applies to all elements) and only that.

**Comment by ngdangtu-vn** [comment]
I see, that's pity but I think this is already very good for type hint atm. I believe many people will appreciate this doc.
