### ISSUE TITLE
spiral example does not work in firefox

### ISSUE THREAD

**Issue by scarf005** [preactjs/preact-www#1161]
| chrome | firefox |
| :-: | :-: |
| <img width="2032" alt="image" src="https://github.com/preactjs/preact-www/assets/54838975/fc787643-16c6-4d54-996d-9562e55b0abb"> | ![image](https://github.com/preactjs/preact-www/assets/54838975/aaa2af4f-0931-44fd-94df-811c9eefdd1a) |

[link](https://preactjs.com/repl/?example=spiral)

using firefox developer edition, 128.0b9 (64-bit, arm64, mac)

**Comment by rschristian** [comment]
Strangely it does sometimes work, but only after you decrease the `COUNT` or `LOOPS` (you can bump them right back up again afterwards).

I'm not sure it's a bug on our end.

**Comment by rschristian** [comment]
Looks like we're running afoul of https://github.com/whatwg/html/issues/4965 (or something related). FF seems to load async while Chrome and Safari do not.

Will get a fix together shortly.
