### ISSUE TITLE
Switching to Preact (from React) - insuffcient information

### ISSUE THREAD

**Issue by danchitnis** [preactjs/preact-www#1172]
I have been trying to convert my React app to Preact using the [Switching to Preact](https://preactjs.com/guide/v10/switching-to-preact) guide which redirects to the [Getting Started](https://preactjs.com/guide/v10/getting-started) and [this section](https://preactjs.com/guide/v10/getting-started#aliasing-react-to-preact) says:

> Note: If you're using Vite, Preact CLI, or WMR, these aliases are automatically handled for you by default.

This information is incorrect because for Preact aliasing to happen in Vite, the [preset-vite](https://github.com/preactjs/preset-vite) package needs to be installed, and the following should be configured in `vite.config.mjs`:

```js
import { defineConfig } from "vite";
import preact from "@preact/preset-vite";

export default defineConfig({
    plugins: [preact()]
});
```

Additionally, these `@babel/core`, `@babel/plugin-transform-react-jsx-development` packages are also required to be installed (but it did not need any configuration).

I appreciate amending this documentation for devs who are new to Preact and want to migrate to it from React.

**Comment by rschristian** [comment]
> This information is incorrect because for Preact aliasing to happen in Vite, the [preset-vite](https://github.com/preactjs/preset-vite) package needs to be installed

I think we wrote that as there's no way to run a Preact + Vite app without `@preact/preset-vite` really -- esbuild nowadays can support a bit of it, but I think the JSX transform alone won't work without our config.

As everyone uses initializers with this preconfigured, it felt a bit redundant.

However, I think we can change this to the following perhaps:

> Note: If you're using Vite (via `@preact/presset-vite`, Preact CLI, or WMR, these aliases are automatically handled for you by default.

---

> Additionally, these `@babel/core`, `@babel/plugin-transform-react-jsx-development` packages are also required to be installed (but it did not need any configuration).

Your package manager should install peer deps automatically.

**Comment by danchitnis** [comment]
> Note: If you're using Vite (via @preact/presset-vite), Preact CLI, or WMR, these aliases are automatically handled for you by default.

Yes, this is clearer and should head the new devs in the right direction.

The issue with the previous Note was that if a dev is both new to Preact and Vite, the Note would have implied that somehow Vite, by default, aliases all React to Preact.

**Comment by rschristian** [comment]
Great, thanks.

Appreciate you taking the time out of your day to open this.
