### ISSUE TITLE
Webmaker app in Demos/Examples goes to a malware site

### ISSUE THREAD

**Issue by g-nor** [preactjs/preact-www#1188]
The link for webmaker app in Demos/Examples (https://preactjs.com/about/demos-examples/) is wrong. The current one redirects to a malware site.

**Comment by rschristian** [comment]
Thanks for letting us know!

Is there an updated link we can use?

**Comment by g-nor** [comment]
Don't know what's the correct link. Just know that the current link is dangerous. Found that while looking through the demos. It should be removed at the very least.

**Comment by rschristian** [comment]
Their GitHub contains this updated link: https://webmaker.app

If you're willing, PR'ing that to all language files would be appreciated, else, I can do it later when I'm back at my desk.

**Comment by g-nor** [comment]
Raised the PR. This was not available in all languages. Assuming it's a good site.

**Comment by rschristian** [comment]
Fixed in #1189
