### ISSUE TITLE
Translate to Japanese

### ISSUE THREAD

**Issue by sotayamashita** [preactjs/preact-www#128]
@developit Could you review this process?

**Process:**
- Copy everything except lang from content/ into content/lang/ja/
- Translate the markdown files 💃
- Add "ja" to the list of languages

I will translate docs with [GitLocalize](https://gitlocalize.com/) which is used in one of the Vue.js projects.

**Comment by developit** [comment]
@sotayamashita That's exactly right!  GitLocalize looks awesome, I hadn't seen that before.  Feel free to hop into the [Slack Chat](https://preact-slack.now.sh) if you aren't already there.

**Comment by sotayamashita** [comment]
@developit  I joined the slack team :smile: . I am an engineer of GitLocalize and We can help translator to keep updated as well.

**Comment by developit** [comment]
I believe there are, yes! We should create a translations channel though, for sure.
