### ISSUE TITLE
Webpackbin link is dead

### ISSUE THREAD

**Issue by jakub-g** [preactjs/preact-www#223]
https://github.com/developit/preact-www/blame/master/content/guide/external-dom-mutations.md#L72-L74

FYI It looks like webpackbin domain has expired was taken over by someone else.

**Comment by developit** [comment]
yikes! We'll need to link to codesandbox/jsfiddle/codepen instead.

**Comment by johnstonbl01** [comment]
@developit Does this code live anywhere anymore? I spoke with Christian (the creator of Webpack Bin), and it's not possible to retrieve any of the old bin code. If the code for this is somewhere already, I can put together the code sandbox and update the docs. If the code isn't available, I can put together an example that tries to match the gif that's currently in the docs.

**Comment by rschristian** [comment]
Going to close this on out as it's been a few years and v8 is far from the current version.

If someone wanted to fix it, we'd be grateful, but I don't think it's much of an issue these days.
