### ISSUE TITLE
Missing transparency in favicon + appears streched

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/preact-www#291]
The current favicon for me looks a bit weird. It doesn't seem to support transparency and the logo is stretched. See this screenshot:

![preact-faviocn](https://user-images.githubusercontent.com/1062408/60791484-10abb200-a164-11e9-8cbd-5ca1e87f2ea6.png)

**Comment by developit** [comment]
Yeah, transparent would be nice here. maybe we ditch the hex for the favicon? Just a slightly rounded purple box with the atom?

**Comment by marvinhagemeister** [comment]
I'm not sure, I feel like the hexagon is what makes our icon more distinct from react. We do have one less ellipsis than they do, but apart from that our icons would look too similar in my opinion. I'm not a logo designer though, so take my opinion with a grain of salt :slightly_smiling_face:
