### ISSUE TITLE
Tasks for the Preact X launch

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/preact-www#307]
Just a little issue to help keep track of things :tada: 

**Features:**
- [x] Switch to Preact-CLI 3
- [x] versioned docs - _Current plan is to have 2 separate folders_
- [x] Switch to X - _Waiting on a fix in `preact-renderer-to-string` to be able to update `preact-markup`_
- [x] ~~Use CSS Animations instead of JS for logo~~ - _Tried that today for a few hours but it's incredibly tricky to get the stroke animation right with just css. Not worth the effort_

**Design:**
- [x] Modernize header + hero
- [x] Update syntax theme

**Content:**
- [x] Divide installation guide into sub pages
  - vanilla js (-> htm) - _no tooling approach_
  - preact-cli - _recommended tooling_
  - webpack/parcel/rollup/browserify - _bring your own_
- [x] Migration Guide 8.x -> X
  - Breaking Changes
- [x] Hooks docs (@JoviDeCroock)

**Bugs:**
- [x] Table of contents is empty on page navigation
- [x] With-TOC layout switches too early to large screen layout

**Bonus (undecided):**
- should we rename `guide` to `docs`?
  - I'd love to have the whole docs navigation in the sidebar. It somehow feels more natural for me.

**Comment by developit** [comment]
RE guide/docs, maybe we keep `guide` but call it `tutorials` and have it be the tutorial-style content? And then move most of its current contents into `docs/`.

> edit: looks like react does this on their site.

**Comment by JoviDeCroock** [comment]
I'll take up Hooks docs, starting this afternoon

**Comment by marvinhagemeister** [comment]
Closing, because the site is ready. The only thing we could do is improve performance even further, but overall I'd be fine with launching it as is. Hope I didn't forgot something and I'm happy to reopen this if something pops up :tada:
