### ISSUE TITLE
Install size-plugin-bot

### ISSUE THREAD

**Issue by kuldeepkeshwar** [preactjs/preact-www#337]
Can we install [size-plugin-bot](https://github.com/kuldeepkeshwar/size-plugin-bot) 😊?

I have done the necessary changes(configuration) required for [size-plugin-bot](https://github.com/kuldeepkeshwar/size-plugin-bot) to work in the [fork](https://github.com/kuldeepkeshwar/preact-www), I will create a pr once [size-plugin-bot](https://github.com/kuldeepkeshwar/size-plugin-bot) is installed

Installation link: https://github.com/apps/size-plugin

cc: @developit

**Comment by marvinhagemeister** [comment]
+1 We were just talking about this earlier today in our slack! It's much nicer than having to always open the CI logs to see the size changes. Happy to review any PRs for that :slightly_smiling_face:

**Comment by kuldeepkeshwar** [comment]
@marvinhagemeister can you install the bot?

**Comment by developit** [comment]
Plugin installed!
