### ISSUE TITLE
Links broken in search

### ISSUE THREAD

**Issue by matthewp** [preactjs/preact-www#425]
Sorry if this is being tracked elsewhere, I couldn't find a related issue. But it appears that the links in search are all broken (at least all I tried are). For example: https://preactjs.com/guide/v10/getting-started/#app

**Comment by developit** [comment]
@matthewp hmm - can you send a screenshot of what you see for preactjs.com? It sounds like you have a zombie service worker 😨

**Comment by matthewp** [comment]
Indeed you are right. Works with another profile but not this one. Fun, i'll investigate.

<img width="1131" alt="preact website down?" src="https://user-images.githubusercontent.com/361671/64452457-6a711f80-d0b4-11e9-900a-5d3daab33c6b.png">

**Comment by developit** [comment]
We rolled out a ServiceWorker upgrade fix that should have addressed this. If anyone is still having issues, feel free to re-open.
