### ISSUE TITLE
Meta titles on link preview

### ISSUE THREAD

**Issue by chulanovskyi** [preactjs/preact-www#442]
Hi! The issue is pretty obvious: 

![image](https://user-images.githubusercontent.com/13966263/66071955-c799ad00-e55c-11e9-9794-a40bbdae8d0d.png)

Something is obviously wrong with one of the meta titles... `[object Object]`. Rendering in Telegram

**Comment by marvinhagemeister** [comment]
@ForsakenHarmony had a look at this in the morning and it's likely caused by our SSR pipeline.
