### ISSUE TITLE
Fragment shorthand not compatible with jsx-factory

### ISSUE THREAD

**Issue by AlexReff** [preactjs/preact-www#480]
See: https://github.com/Microsoft/TypeScript/issues/20469

> JSX fragment is not supported when using --jsxFactory ts(17016)

Documentation should be updated to clarify how to use `<></>` Fragment shorthand syntax. I could not get it working correctly.

**Comment by AlexReff** [comment]
Would you accept a pull request with a note for Typescript users, or are you planning on having entirely separate documentation for Typescript?

**Comment by marvinhagemeister** [comment]
A note is perfectly fine for now. It's better than what we have right now :+1: Happy to review any PRs :tada: :100: 

A dedicated TS page may be something for later.

**Comment by rschristian** [comment]
At some point a dedicated TS page was added with info on how to set the `jsxFragmentFactory`, so I'll close this on out.
