### ISSUE TITLE
Only old site shows until browser data cleared

### ISSUE THREAD

**Issue by leafi** [preactjs/preact-www#485]
Hey,

I think I probably last visited preactjs.com several months ago. Certainly before Preact X documentation was present.

It seems I had a service worker installed that happily presented me the old site repeatedly, until I manually cleared site data stored in my browser and the new website finally appeared. Very nice it is, too!

A screenshot of the old site, presented despite its age:
![Screenshot from 2019-11-24 09-57-35](https://user-images.githubusercontent.com/2166555/69493080-2ebf4800-0ea2-11ea-920b-f2012fc1485c.png)

Post-cookie clear, cache clear, and SW unregister (Chrome 'Clear site data' button) - and after I loaded the new site in a new tab - here's the old tab, on the Service Worker page in Chrome DevTools:

![Screenshot from 2019-11-24 10-01-52](https://user-images.githubusercontent.com/2166555/69493106-7cd44b80-0ea2-11ea-816b-9acab756a87d.png)

Note the 'clients' list including both the old (versionless) getting started guide and the new v10 what's new page.

When is the old service worker invalidated? I spent a good 25 mins futzing around in the browser, trying to understand why the live site had nothing about v10 compared to this repository. I was persistently presented the old site.

**Comment by developit** [comment]
This is super painful, and I'm sorry. Prateek and I had been throwing ideas back and forth for a while on how to upgrade, but never came up with anything that could work. The problem stems from us having no way to update the cached ServiceWorker code running in your browser - it's stuck at its current version until the end of time.

However! I looked into things again today and miraculously stumbled onto a solution. It's implemented in #489 - the new ServiceWorker has the same URL as the old one, and I've added a sort of "power-on self test" bit that detects the broken situation you ran into and forces the new version to install.

Without doing anything, it should show the old website for a split second, then switch to the new one (without breaking the URL!).
