### ISSUE TITLE
This document has errors

### ISSUE THREAD

**Issue by yujingwyh** [preactjs/preact-www#495]
https://preactjs.com/guide/v10/api-reference
Render code example with replaceNode parameter
```
// After render:
// <div id="container">
//   <div>bar</div>
//   <div id="target">
//     <div>foo</div>
//   </div>
// </div>
```
should be
```
// After render:
// <div id="container">
//   <div>bar</div>
//   <div id="">foo</div>   
// </div>
```

**Comment by developit** [comment]
You're correct! Actually I think it's worth changing this example a bit, since swapping the element type of a root node doesn't really demonstrate diffing much at all.
