### ISSUE TITLE
[Documentation] Mobile navigation on your guide is confusing

### ISSUE THREAD

**Issue by mcclure** [preactjs/preact-www#499]
Hi. I am learning preact. Yesterday I was reading the docs (click "getting started" from preactjs.com) on my laptop. Then I had to get on the bus so I switched to my phone. I immediately got really confused because the "guide", on the laptop, had a nice menu of sections on the left. But the mobile version seemed to ONLY offer the "getting started" page. I wouldn't have even known that there were more sections if I hadn't seen the desktop version first. I tried clicking the "Hamburger menu" cuz sometimes that's where websites keep menus but it wasn't there. I was reduced to typing "preact hooks" and "preact context" and such into Google because I remembered some section names from the desktop version.

Today, the next day, I opened up this page to file a github issue saying there's no way to switch between sections in your guide. And now, only just now, I'm realizing there is a way. There's a red circle in the bottom right with a `<>` in it, and if you tap it it turns sideways(?) and a menu scrolls in from the left? I've never seen a widget like this before. I really don't know how I would have guessed that's the "sections of the guide" website, or thought to tap it, if I were just reading the website. I didn't even notice it yesterday. A lot of websites have random crud like feedback buttons in the corner so I guess I've learned to sort of tune that stuff out. :(

My recommendation is you show your sections through some method clearer than a floating button with a `<>` icon. I don't know what the best way to do this is but a link at the top or bottom that says "table of contents" would make sense to me.

**Comment by marvinhagemeister** [comment]
Awesome, thanks for the detailed feedback. I can see how chat icons and other stuff in the bottom right corner have trained us to ignore that section of a page :+1:

**Comment by developit** [comment]
I like this recommendation. A quick fix for now might be to expand the icon to include a text label ("Guide"), and change the icon.

Here's a quick mock of what I thought that might look like:

<img src="https://user-images.githubusercontent.com/105127/70456695-a2ee1400-1a7c-11ea-8f72-cb0fe15af51b.png" width="467">

**Comment by developit** [comment]
Another change that might help is moving the floating menu button to the center, and also having a second inline version at the top of each page:

<img src="https://user-images.githubusercontent.com/105127/70459420-252d0700-1a82-11ea-8fd0-25563ef2f9a4.png" width="483">

**Comment by developit** [comment]
We shipped this! Likely still worth discussing a merged hamburger + nav menu (#557) though.
