### ISSUE TITLE
Add bundling/tooling walkthroughs/builders

### ISSUE THREAD

**Issue by developit** [preactjs/preact-www#5]
As suggested by @katopz:
- [ ] How to bundle properly, best practise (and maybe roadmap) : rollup, webpack, jspm

Perhaps something similar to http://babeljs.io/docs/setup/

**Comment by marvinhagemeister** [comment]
We have a section about setting up the aliases for various bundlers/testing tools. On top of that we have a section for a no-tooling approach via `htm` or one for `preact-cli`. So I don't think we need to add mini-webpack docs or something similar. I'd rather refer to their docs :+1:
