### ISSUE TITLE
REPL errors unreadable

### ISSUE THREAD

**Issue by remy** [preactjs/preact-www#528]
See screenshot from [this code](https://preactjs.com/repl?code=function%20Counter()%20%7B%0A%20%20const%20%5Bvalue%2C%20setValue%5D%20%3D%20useState(0)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%3C%3E%0A%20%20%20%20%20%20%3Cdiv%3ECounter%3A%20%7Bvalue%7D%3C%2Fdi%0A%20%20%20%20%20%20%3Cbutton%20onClick%3D%7B()%20%3D%3E%20setValue(value%20%2B%201)%7D%3EIncrement%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3Cbutton%20onClick%3D%7B()%20%3D%3E%20setValue(value%20-%201)%7D%3EDecrement%3C%2Fbutton%3E%0A%20%20%20%20%3C%2F%3E%0A%20%20)%0A%7D)

![Screenshot 2020-02-03 at 21 32 01](https://user-images.githubusercontent.com/13700/73692655-a8f32080-46cc-11ea-9267-3be4edacfb82.png)

I know the "eye saver" on my monitor is partly at play here, but the contrast on the text and the background is way way too close.

If someone can point me to the REPL CSS I'd be happy to change it to a different colour in a PR.

**Comment by marvinhagemeister** [comment]
Good catch! The CSS for that can be found here: https://github.com/preactjs/preact-www/blob/a261c5251b5cfdfbf55581c47624882c87c79dcb/src/components/code-editor/style.less#L5-L26

**Comment by blenderskool** [comment]
@marvinhagemeister Is this still being worked on? I would like to work on this :innocent:

**Comment by marvinhagemeister** [comment]
@blenderskool It's free to take, there isn't anybody working on this yet 👍

**Comment by blenderskool** [comment]
@marvinhagemeister I was experimenting with the error highlighting and decided on a red underline instead of background color as many editors follow this.
I have changed the color of the red box slightly to improve contrast ratio. Let me know your thoughts.

![image](https://user-images.githubusercontent.com/21107799/91631263-fb43b800-e9f5-11ea-9c90-14c5a1824af5.png)
