### ISSUE TITLE
Convert all examples in Home page to Hooks

### ISSUE THREAD

**Issue by nainardev** [preactjs/preact-www#531]
Hooks are easier for beginners

**Comment by JoviDeCroock** [comment]
We could partially convert some but `hooks` aren't really part of `preact-core` atm so we should certainly keep a few classic examples in place.

**Comment by nainardev** [comment]
Is there a plan to include `hooks` in `preact/core` ?

**Comment by JoviDeCroock** [comment]
We've been on and off about it since `core` is known as the 3KB framework while with hooks this is 4KB

**Comment by nainardev** [comment]
So, hooks aren't completely supported?

**Comment by JoviDeCroock** [comment]
They are, it just required an import from `preact/hooks` at the moment. Which isn't a bad thing nothing is limiting from making a file named `preact.js`:

```
export * from 'preact';
export * from 'preact/hooks';
```

Where are you getting that impression from that it's not supported?

**Comment by developit** [comment]
I don't want to give people the impression Preact implies hooks. Less than half of people I talk to have even used them, and class components aren't likely to go anywhere for a long time. Hooks examples may appear easier to some, but the details of how they work are much harder to explain.
