### ISSUE TITLE
Please add a LICENSE file to this repo

### ISSUE THREAD

**Issue by mbrukman** [preactjs/preact-www#566]
While both [`package.json`][package-json] and the [`README.md`][readme] specify the MIT license, this repo is missing an explicit `LICENSE` file at the top of the repo, which means it doesn't get the [nice GitHub license badge][github-license-badge].

Please consider adding an explicit `LICENSE` file to the repo with the contents of the MIT license, as is the case in other PreactJS repos.

Thanks!

[package-json]: https://github.com/preactjs/preact-www/blob/898d7dab96e2c66dda1d9e052826226dd78950d7/package.json#L70
[readme]: https://github.com/preactjs/preact-www/blob/898d7dab96e2c66dda1d9e052826226dd78950d7/README.md#license
[github-license-badge]: https://github.blog/2016-09-21-license-now-displayed-on-repository-overview/

**Comment by marvinhagemeister** [comment]
Good catch, we somehow missed that :+1: It has now been added :tada:
