### ISSUE TITLE
Add docs about SVG normalization

### ISSUE THREAD

**Issue by teodragovic** [preactjs/preact-www#615]
Going over issues in main repo (https://github.com/preactjs/preact/issues/2404, https://github.com/preactjs/preact/issues/1061, https://github.com/preactjs/preact/issues/813, https://github.com/preactjs/preact/issues/1940), misunderstanding about SVG props normalization seems common enough to be added into "Differences to React" section (note about following DOM specs might imply this but it's not very obvious).

IMO @andrewiggins already provided great explanation [here](https://github.com/preactjs/preact/issues/1940#issuecomment-548703893) that can be used as basis.

I would gladly submit PR if that's ok?

**Comment by developit** [comment]
@teodragovic It seems like most of those issues were fixed. Is the idea that this would go under "Differences to React" with an explanation that while `preact` does not perform normalization, `preact/compat` addresses the differences?

**Comment by teodragovic** [comment]
Yep, exactly.

**Comment by marvinhagemeister** [comment]
sounds good to me. We should point out that Preact itself follows the various HTML specs in naming and that only compat normalizes those like in React.
