### ISSUE TITLE
Improve UX for deprecated doc pages

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/preact-www#684]
See https://twitter.com/mcclure111/status/1308441745475108866

> Hm, I do see that banner. I don't remember if I clicked it before.
>
> I guess when I click it it says "Oops, that page vanished". Possibly I saw that but then I didn't know > if it meant the feature was removed or if the page was moved.

The user was on the 8.x "Linked State" page clicked on the banner and was greeted with a "Page not found" error. There is no mention that this feature was deprecated.

**Comment by mcclure** [comment]
In the *very specific* case of linkState, if you're going to put in a "removed!" stub, you could link to the [standalone linkstate module](https://www.npmjs.com/package/linkstate). Unless you think getting people to use the linkstate module will create additional support headaches for you :)

**Comment by rschristian** [comment]
This was "fixed" a little bit ago; for missing v10 equivalent docs, we simply send the user to `/v10/getting-started`.

Hopefully this suffices.
