### ISSUE TITLE
state example in the documentation

### ISSUE THREAD

**Issue by boan-jfm** [preactjs/preact-www#698]
You will get an inspection error by doing this:

https://github.com/preactjs/preact-www/blame/master/content/en/guide/v10/components.md#L47

![image](https://user-images.githubusercontent.com/13201214/96561641-1e853800-12c0-11eb-99f7-de1c8e19299c.png)

Version:
preact@10.5.5

**Comment by marvinhagemeister** [comment]
@boan-jfm What does your interface `SiteCardState` look like?

**Comment by boan-jfm** [comment]
> @boan-jfm What does your interface `SiteCardState` look like?

```
interface SiteCardState {
    multi_priority_unfolded: boolean
}
```

**Comment by boan-jfm** [comment]
@marvinhagemeister

Seems to work, I tried:
```
    constructor(props) {
        super(props);

        this.state = {multi_priority_unfolded: false};
    }
```

But I may have been on an old version of Preact (https://stackoverflow.com/questions/51074355/cannot-assign-to-state-because-it-is-a-constant-or-a-read-only-property), I didn't read the updated inspection message after the update..

- I am not sure what has changed in the state declaration - which make it work...?

**Comment by marvinhagemeister** [comment]
@boan-jfm The error pops up because `{ time: number }` is a different type compared to your `SiteCardState` which is `{ multi_priority_unfolded: boolean }`. The latter doesn't have a `time` property.

The thread on StackOverflow is unrelated.
