### ISSUE TITLE
Content doesn't update correctly on translation

### ISSUE THREAD

**Issue by Remeic** [preactjs/preact-www#700]
I'm updating some pages for the italian translation, but i have strange behaviour on translated pages.
On homepage i get the error `index.js?cd39:97 Uncaught (in promise) TypeError: Cannot read property '1' of null`
On specific pages i don't have this error but the issue is still present.

I believe video can be very useful: 
https://youtu.be/hPsY6OrfEPI

Reproducibility: 
**Repo:** https://github.com/Remeic/preact-www 
**branch:** feature/italian

**Comment by developit** [comment]
Yikes! I think that's something to do with the parsing of YAML frontmatter in documentation files. I don't see anything in your branch that would cause such issues though...

**Comment by Remeic** [comment]
> Yikes! I think that's something to do with the parsing of YAML frontmatter in documentation files. I don't see anything in your branch that would cause such issues though...

Can I perform other tests to be able to resolve the problem or get more details? Thanks in advance Jason!

**Comment by rschristian** [comment]
Sorry for the long delay.

The HTML is being indented with four spaces -- per the markdown spec, this makes it a code block, which then threw an error as these code blocks weren't given a class specifying the code type for prism.

```diff
<section class="home-section">
-    <img src="/assets/home/metal.svg" alt="metal">
-
-    <h2>Più vicino al DOM</h2>
+  <img src="/assets/home/metal.svg" alt="metal">
+
+  <h2>Più vicino al DOM</h2>
```

It's not the most robust system in the world, admittedly.
