### ISSUE TITLE
x render eat the last el 

### ISSUE THREAD

**Issue by dazhoudotnet** [preactjs/preact-www#714]
in v10 upgrade-guide 

```
// Existing markup:
<body>
  <div>hello</div>
</body>

render(<p>foo</p>, document.body);
render(<p>bar</p>, document.body);

// Preact X output:
<body>
  <p>bar</p>
  <div>hello</div>
</body>
```

Actually Preact X output is:
```
<body>
  <p>foo</p>
</body>
```

**Comment by developit** [comment]
This is only true in `preact/compat`. Like version 8, Preact X does not remove unmatched elements during top-level render():

https://jsfiddle.net/developit/5yug70po/

**Comment by dazhoudotnet** [comment]
https://jsfiddle.net/5ge0o3Lj/1/

and example in guide (without modify):

https://preactjs.com/repl?code=%2F%2F%20Existing%20markup%3A%0A%3Cbody%3E%0A%20%20%3Cdiv%3Ehello%3C%2Fdiv%3E%0A%3C%2Fbody%3E%0A%0Arender(%3Cp%3Efoo%3C%2Fp%3E%2C%20document.body)%3B%0Arender(%3Cp%3Ebar%3C%2Fp%3E%2C%20document.body)%3B%0A%0A%2F%2F%20Preact%20X%20output%3A%0A%3Cbody%3E%0A%20%20%3Cp%3Ebar%3C%2Fp%3E%0A%20%20%3Cdiv%3Ehello%3C%2Fdiv%3E%0A%3C%2Fbody%3E


why render overwrite the last or first div ?
