### ISSUE TITLE
README slack links + badges are broken

### ISSUE THREAD

**Issue by zackkrida** [preactjs/preact-www#725]
Slack badges are broken in this README and that of https://github.com/developit/preact. There are additionally a few different chat links floating around:

- https://chat.preactjs.com/
- https://preact-slack.now.sh/ (broken)
- https://preact-slack.now.sh/badge.svg (broken)

**Comment by developit** [comment]
Ah, yep - those were hosted on Now 1.0 which was turned down earlier this year. There's no convenient way to show the badge anymore, so maybe we just replace it with a static one.  The chat.preactjs.com URL is the correct slack FWIW.

**Comment by thawkin3** [comment]
Here's one possible solution to consider using just a static badge from Shields.io: https://github.com/preactjs/preact-www/pull/765
