### ISSUE TITLE
Forbid worthless comment

### ISSUE THREAD

**Issue by 38elements** [preactjs/preact-www#738]
I think that negative comments based on subjectivity, such as the following, should be prohibited, since it is  no value. I think such comments are dangerous because they are versatile.
"I think your adding description is what eventone knows, worth mentioning?"

**Comment by JoviDeCroock** [comment]
The original comment you are referring to is the following I guess:

> I think it’s not only a type for children that’s added to props but also the property children in general. Worth mentioning?

Which in no means refers to what you are saying, a PR comment should be taken constructively. You can make everything sound negative as an OSS community member it’s up to you to handle comments constructively and with healthy debate. This is part of our CoC https://github.com/preactjs/preact/blob/master/CODE_OF_CONDUCT.md#our-standards

The comment is in no way negative, it’s how you choose to interpret it.

**Comment by 38elements** [comment]
I don't think subjective opinions are worth it.
Would you please tell me the worth of this comment?
You say that comments should be processed constructively.
I have not seen you are commented like that comment in here.

**Comment by JoviDeCroock** [comment]
You could've responded that the OP should elaborate on said issue, there is no mal-intent in a phrase like that. It challenges a change in code "I think it’s not only a type for children that’s added to props but also the property children in general" and then proceeds to ask if this is worth mentioning in your opinion.

> I have not seen you are commented like that comment in here.

I'm not quite sure what you mean by this but you can look at PR's in the Preact (and other) ecosystems how comments are approached by anyone on the team and outside of it.
