### ISSUE TITLE
Forbid worthless comment part 2

### ISSUE THREAD

**Issue by 38elements** [preactjs/preact-www#740]
@JoviDeCroock
> Preact also ships a `FunctionComponent` type to annotate anonymous functions. `FunctionComponent` also adds a type for `children
> I think it’s not only a type for children that’s added to props but also the property children in general.

This comment is incorrect. Component class constructor's  props does not have children. Since He does not know it, he made mistaked.
https://github.com/preactjs/preact-www/pull/720
Therefore, this comment is no value.

> Why do you feel this comment is offensive towards you?

Most people send pull request because they think it's worth it.
I think it is unnatural to ask if it is worth it.

>>I have not seen you are commented like that comment in here.
> 
> I'm not quite sure what you mean by this

I feel that the comments made by some European newcomer differ depending on whether European or not.

**Comment by marvinhagemeister** [comment]
>> Why do you feel this comment is offensive towards you?

> Most people send pull request because they think it's worth it.
> I think it is unnatural to ask if it is worth it.

The phrase "Worth mentioning?" does translate to "Do you think we should add this too?". It doesn't suggest in any way that something is wrong with the PR. I have no clue how you made that connection and why you think it's up to everyone else to disprove your interpretation.

It's been going on for about two weeks now and we've reached out multiple times out to you and explained the situation and the misunderstanding. You've stretched our goodwill pretty thin by now. You're recent comments violate the following sections of our [Code of Conduct](https://github.com/preactjs/preact-www/blob/master/CODE_OF_CONDUCT.md#our-standards):

- Being respectful of differing viewpoints and experiences
- Gracefully accepting constructive criticism
- Showing empathy towards other community members

If this continues we see no other option other than to invoke the ban functionality. We hope that it doesn't come to this, but ultimately that's up to you.

**Comment by 38elements** [comment]
@marvinhagemeister 
> Gracefully accepting constructive criticism

That comment is a subjective comment based on wrong knowledge and not constructive.

> The phrase "Worth mentioning?" does translate to "Do you think we should add this too?". It doesn't suggest in any way that something is wrong with the PR. I have no clue how you made that connection and why you think it's up to everyone else to disprove your interpretation.

In my culture, that comment is a insulting comment. I have never seen Europeans is said this in here.

You are commenting on Western values. If "Western values take precedence" is added to rule, I will agree with you.
