### ISSUE TITLE
The website is down - because of non-javascript client?

### ISSUE THREAD

**Issue by iwikal** [preactjs/preact-www#744]
Could just be a coincidence, but I just visited reactjs.org with javascript disabled in my browser. After one or two navigations, the server stopped responding completely.

**Comment by marvinhagemeister** [comment]
Looks like you confused Preact with React. This repository is for the website that's hosted at https://preactjs.com . The issue tracker for https://reactjs.org can be found here: https://github.com/reactjs/reactjs.org

**Comment by iwikal** [comment]
That's a typo, I meant preactjs.org :grimacing:

**Comment by marvinhagemeister** [comment]
There is no preactjs.org either, only preactjs.com 🙃 Just tried it and I'm able to navigate the site just fine with JS disabled.

**Comment by iwikal** [comment]
Strange. For me, https://preactjs.com redirects to https://preactjs.org. Maybe I have an old service worker that refuses to go away? Did you use to host it at https://preactjs.org?

**Comment by iwikal** [comment]
I restarted my browser and just like that, the problem is gone. I've probably pwned myself somehow.

**Comment by marvinhagemeister** [comment]
That's strange. We do use a service worker, but I can't recall a time where we used the domain `preactjs.org`. Happy to hear that all seems to be working now for you 👍

**Comment by developit** [comment]
We now redirect preactjs.org to preactjs.com. Thanks for the heads-up!
