### ISSUE TITLE
Adding the slack invite link to website

### ISSUE THREAD

**Issue by brkn** [preactjs/preact-www#767]
Hi, I had to do bunch of googling for finding the community chat server.

* Looked everywhere at the https://preactjs.com but no link to a community server,
* then searched `"preact" discord` first result is this: https://twitter.com/_developit/status/821067365676941314 so preact uses slack but link was dead,
* then searched `"preact" slack`  and this is the top result on google https://github.com/preactjs/preact/issues/2696 and the link works.

So a link to slack workspace from preactjs.com could be nice imo.

**Comment by binyamin** [comment]
If someone wants to work on this, the link http://chat.preactjs.com should be good (see https://github.com/preactjs/preact/issues/2696#issuecomment-673582196).
