### ISSUE TITLE
Proposal: Move language picker to the header

### ISSUE THREAD

**Issue by rschristian** [preactjs/preact-www#899]
[translated]

> I found this after reading to the bottom.....
> 
> ![temp](https://user-images.githubusercontent.com/33403762/189449326-71bb08e0-be0b-47e5-a86c-fcf86edd26cc.PNG)

Source: https://twitter.com/su8ru_/status/1568246589545938944

Having the language picker hidden away at the bottom of the page likely makes these situations occur more than they should. Moving to the header (which is always visible) should help this a lot.

**Comment by vitormalencar** [comment]
I remember that I had a PR done for that some long time ago,
also, I remember that the blocker was that the header was a bit full of links

**Comment by rschristian** [comment]
Thanks for mentioning that! Will base off of [it](https://github.com/preactjs/preact-www/pull/487) if I do something with this.

Not really a fan of flags, it works for a handful of countries and that's about it. What flag do you show for English, the American or UK flag? For Spanish do you show Spain or Mexico? Etc.

I think we can add a symbol into the header and do the drop down from it. Something along the lines of this:

![temp](https://user-images.githubusercontent.com/33403762/189880046-0a0d928c-2023-476a-bd27-0c36caa71ee0.PNG)
