### ISSUE TITLE
Broken navigation links on the signals guide

### ISSUE THREAD

**Issue by nibble0101** [preactjs/preact-www#944]
When you navigate to the [signals documentation](https://preactjs.com/guide/v10/signals/), there are navigation links for navigating to the appropriate sections of the documentation. However, the links under the API section(check screenshot below) are broken because of the differences between the generated `id` and the corresponding `href` attributes. For a heading with the text `signal(initialValue)`, the generated `href` attribute for the navigation link has a value of `#signal-initialvalue` while the corresponding heading `id` is `signalinitialvalue`
![image](https://user-images.githubusercontent.com/52580190/203924952-d07ce47b-6c12-4b16-9127-027e6571f691.png)

**Comment by rschristian** [comment]
The fix should be deployed shortly. Thanks for letting us know!

**Comment by nibble0101** [comment]
> The fix should be deployed shortly. Thanks for letting us know!

Thanks for fixing. That was fast.
