### ISSUE TITLE
"?lang=en" in the footer.

### ISSUE THREAD

**Issue by vimalsaraswat** [preactjs/preact-www#948]
There is "?lang=en" as below in the footer alongside the language selection dropdown menu.
![Screenshot_2022-12-14-20-07-45-895_com android chrome](https://user-images.githubusercontent.com/106457983/207624546-9299b347-d5c0-4ed6-a526-d6074d2c0cc2.png)
I don't know if it is intentional or not.

**Comment by rschristian** [comment]
It's intentional, yes. That's a URL query parameter that can be used to link to a certain page in a certain language. For example: https://preactjs.com/?lang=de

**Comment by vimalsaraswat** [comment]
Ok, now i got it, thankyou for explaining it.thankyou.
