### ISSUE TITLE
Update @preact/signals.

### ISSUE THREAD

**Issue by MicahZoltu** [preactjs/preact-www#958]
This project uses `@preact/signals` version `1.0.0`, which I believe means the REPL uses `1.0.0`.  `useSignalEffect` does not appear to be present in `1.0.0`, which means it cannot be used in the REPL.

What is the process for updating a dependency on this project?  Should I just submit a PR that updates package.json and rebuilds the lockfile?

**Comment by rschristian** [comment]
> Should I just submit a PR that updates package.json and rebuilds the lockfile?

Yup, that'd be great if you're willing.
