### ISSUE TITLE
Somewhat confusing introduction to Components at the start of the tutorial

### ISSUE THREAD

**Issue by masto** [preactjs/preact-www#974]
https://github.com/preactjs/preact-www/blob/master/content/en/tutorial/01-vdom.md, under "Detour: Components", there is an example that says "[...] we don't need to write that last `render()` line anymore".

But if you actually try that example in the REPL, it does not work. In fact, the default code block loaded up ends with a `render()` line:

`render(<App />, document.getElementById("app"));`

As I am brand new to Preact, I found this discrepancy between the statement above and the actual behavior confusing. I expect it will make more sense later when there is presumably a full treatment of Components, but it might be better not to have any head-scratchers on page 1 of the tutorial.

**Comment by rschristian** [comment]
Indeed, we can word that better.

> ...HTML elements like `<p>` are just one of two types of Virtual DOM elements. The other type is a Component, which is a Virtual DOM element where the type is a function instead of a string like `p`.

> ...which will be rendered for us so we don't need to write that last `render()` line anymore:

What this is trying to say is that, like `<p>`, you can use components (`<App>`) as building blocks. You don't need to (and shouldn't) add a `render()` if your component is meant to be used as a building block in something else, if that makes sense.

_Something_ will need to be rendered, however.
