### ISSUE TITLE
Signals example doesn't work

### ISSUE THREAD

**Issue by masto** [preactjs/preact-www#978]
https://preactjs.com/repl?example=todo-list-signals

Expected behavior: "a fully working todo app" as the link on https://preactjs.com/guide/v10/signals#building-the-ui calls it.

Observed behavior: page loads, but no functionality (add, check, delete all do nothing)

I tried Chrome and Safari on my Mac, with extensions disabled, so I think I've ruled out that it's a local browser issue.

**Comment by developit** [comment]
Ah darn, it looks like I must have broken this in #971. Will fix.
