### ISSUE TITLE
Translate to Russian

### ISSUE THREAD

**Issue by developit** [preactjs/preact-www#98]
/cc @amelekhin @iamale and @kipruss who mentioned they might want to help out!

#### Process:

- Copy everything except `lang` from `content/` into `content/lang/ru/`
- Translate the markdown files 💃 
- Add "ru" to the [list of languages](https://github.com/developit/preact-www/blob/master/src/config.json#L7)

**Comment by kipruss** [comment]
Ok, I will try

**Comment by iamale** [comment]
I can join in sometime this weekend, too, yeah

**Comment by kipruss** [comment]
I have added files for Russian translation and translated a 404 file for begin in this PR https://github.com/developit/preact-www/pull/99

**Comment by kipruss** [comment]
Maybe it would be useful to create a separate branch "russian-translation" for this issue

**Comment by iamale** [comment]
@kipruss Let's just collaborate in your fork (in the [`russian-translation`](https://github.com/kipruss/preact-www/tree/russian-translation) branch), maybe?

**Comment by kipruss** [comment]
@iamale I do not mind

**Comment by amelekhin** [comment]
It also would be great if we had

**Comment by iamale** [comment]
How about Gitter then? https://gitter.im/preact-russian

**Comment by developit** [comment]
@amelekhin @iamale - can always use the [Preact Slack chat](https://preact-slack.now.sh). Anyone can create channels there :)

**Comment by iamale** [comment]
@developit Could you please elaborate a bit on that

> **Efficiency:** Effective memory usage _(recycling, avoiding GC thrash)

line in `about/project-goals`? @amelekhin is translating it now and we're stuck.

**Comment by amelekhin** [comment]
@developit and the same thing about Component and element recycling/pooling. Could you please explain these processes in a few words?

**Comment by developit** [comment]
sure!

> Efficiency: Effective memory usage _(recycling, avoiding GC thrash)

Preact creates and stores as few objects as possible, and re-uses objects where possible. Re-using objects allows Preact to keep a more constant memory footprint, so that the JavaScript Engine's Garbage Collector is invoked less often (garbage collection is expensive, and blocks when it kicks in).  "GC Thrash" refers to what happens when these techniques are not used - the garbage collector has to run often, which results in slow frames (referred to as "jank").

> Component and element recycling/pooling

This one is actually similar to the above point.  When Preact unmounts/removes Components and DOM Elements, it stores them.  When a future render needs the same type of Component/Element, Preact will attempt to use one of the cached copies if it exists.

Side note:  Element recycling is very likely getting removed in Preact 8, though Component recycling will remain and covers 99% of the cases Element recycling was supposed to handle.

**Comment by amelekhin** [comment]
That's a very comprehensive answer! Thanks.

**Comment by jt3k** [comment]
for translators:
I compiled a roadmap for translating preactjs.com into Russian 
https://workflowy.com/s/Ex8V.CA7S7SntoF 

This list can be edited by everyone.
This will help us to synchronize our actions, and not to repeat someone else's work
