### ISSUE TITLE
signals not work in the REPL of official website

### ISSUE THREAD

**Issue by faxinwang** [preactjs/preact-www#981]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
the todo list (signals) example do not work in the REPL of the  official website. 
date: 2023/3/22

https://preactjs.com/repl?example=todo-list-signals

**To Reproduce**

1. Go to https://preactjs.com/repl?example=todo-list-signals
2. input some text int the input box
3. click add button, the item does not add to todo list.
4. click the x button, the item does not deleted.

**Comment by rschristian** [comment]
Thanks for letting us know!

We already have #978 to track this, so lets close this one out as a duplicate.
