### ISSUE TITLE
server-side-rendering

### ISSUE THREAD

**Issue by jespertheend** [preactjs/preact-www#984]
[server-side-rendering.md](https://github.com/preactjs/preact-www/blob/master/content/en/guide/v10/server-side-rendering.md) contains a section about pretty mode. But I think support for pretty mode has been removed?
When I look at the source code of preact-render-to-string there doesn't seem to be a third parameter for `renderToString`

**Comment by andrewiggins** [comment]
Pretty printing had been moved to `preact-render-to-string/jsx` path so change the import in that example from `import render from 'preact-render-to-string';` to `import render from 'preact-render-to-string/jsx';`. [Options to control the output are documented here](https://github.com/preactjs/preact-render-to-string/blob/a9817ff0f177d58f5c8401bd3fce9d9c948a8eec/src/jsx.js#L72).

We need to update the website to reflect this change. Thanks for the bug report!
