### ISSUE TITLE
No docs for `useSignalEffect`?

### ISSUE THREAD

**Issue by rmneux** [preactjs/preact-www#992]
It appears there is no documentation for `useSignalEffect`. Can I contribute one?

<https://preactjs.com/guide/v10/signals>

**Comment by rschristian** [comment]
> Can I contribute one?

Absolutely, we'd love if you could to that.

It should just be a single line mimicking what we have for `useSignal` & `useComputed`

**Comment by rmneux** [comment]
Thank you I've just sent a PR
